import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Car, Wallet, Users, Clock, ShieldCheck, MapPin, Bell, Navigation, AlertTriangle } from 'lucide-react';
import './styles.css';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000';
const bairros = ['Centro','Brisas do Catu','Urupiara','Céu Azul','Informa','Santa Terezinha','Petrolar','Mangalô','Boa União'];

function money(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));}
async function apiGet(path){const r=await fetch(`${API_BASE_URL}${path}`); if(!r.ok) throw new Error(`HTTP ${r.status}`); return r.json();}
async function apiPost(path, params={}){const q=new URLSearchParams(params).toString(); const r=await fetch(`${API_BASE_URL}${path}${q?'?'+q:''}`,{method:'POST'}); if(!r.ok) throw new Error(await r.text()); return r.json();}

function fallbackPricing({distanceKm, occupants, originZone, destinationZone, goesBeyondCenter}){
  const shared = Number(occupants) >= 4;
  const multiplier = ['Céu Azul','Informa'].includes(originZone)||['Céu Azul','Informa'].includes(destinationZone)?1.3:['Brisas do Catu'].includes(originZone)||['Brisas do Catu'].includes(destinationZone)?1.1:1;
  const base = shared ? 4.6 + Math.max(0, Number(distanceKm)-5)*0.65 + (goesBeyondCenter?Number(distanceKm)*0.45:0) : Math.max(12, Number(distanceKm)*2.8+5);
  const raw = base * multiplier;
  const rounded = raw <= 12 ? Math.round(raw/0.2)*0.2 : Math.round(raw/0.5)*0.5;
  return {pricing_policy:'sem_dinamica', mode: shared?(multiplier>1?'shared_comfort':'lotacao_popular'):'solo', price_per_passenger: Math.round(rounded*100)/100, total_trip_price: Math.round(rounded*Number(occupants||1)*100)/100, occupants:Number(occupants||1), estimated_wait_minutes: Math.min(15,3+(shared?4:0)+(Number(distanceKm)>=10?3:0)), comfort_required: multiplier>1, matching_priority: multiplier>1?'comfort':shared?'cheapest':'fastest', fallback:true};
}

function Card({children, className=''}){return <div className={`card ${className}`}>{children}</div>}
function Pill({children,type='default'}){return <span className={`pill ${type}`}>{children}</span>}
function Button({children,onClick,kind='',disabled=false}){return <button className={`button ${kind}`} disabled={disabled} onClick={onClick}>{children}</button>}

function Passageiro(){
  const [origem,setOrigem]=useState('Brisas do Catu');
  const [destino,setDestino]=useState('Centro');
  const [distanceKm,setDistanceKm]=useState(7);
  const [occupants,setOccupants]=useState(4);
  const [goesBeyondCenter,setGoesBeyondCenter]=useState(false);
  const [pricing,setPricing]=useState(()=>fallbackPricing({distanceKm,occupants,originZone:origem,destinationZone:destino,goesBeyondCenter}));
  const [ride,setRide]=useState(null); const [match,setMatch]=useState(null); const [apiStatus,setApiStatus]=useState('fallback'); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  async function quote(){setLoading(true);setError('');try{const p=new URLSearchParams({distance_km:String(distanceKm),occupants:String(occupants),goes_beyond_center:String(goesBeyondCenter),origin_zone:origem,destination_zone:destino}); const data=await apiGet(`/pricing/city-ride?${p}`); setPricing(data); setApiStatus('online');}catch(e){setPricing(fallbackPricing({distanceKm,occupants,originZone:origem,destinationZone:destino,goesBeyondCenter}));setApiStatus('fallback');setError('API indisponível. Usando cálculo local.');}finally{setLoading(false)}}
  async function createRide(){setLoading(true);setError('');setMatch(null);try{const data=await apiPost('/rides/create',{passenger_user_id:'passenger-demo',ride_type:Number(occupants)>=4?'shared_city':'solo',origin_neighborhood:origem,destination_neighborhood:destino,distance_km:String(distanceKm),occupants_expected:String(occupants),accepts_sharing:String(Number(occupants)>=2),goes_beyond_center:String(goesBeyondCenter)});setRide(data);setApiStatus('online');}catch(e){setRide({id:`local-${Date.now()}`,origin_neighborhood:origem,destination_neighborhood:destino,price_per_passenger:pricing.price_per_passenger,total_trip_price:pricing.total_trip_price,local:true});setApiStatus('fallback');setError('Corrida criada localmente. Suba o backend para persistir.');}finally{setLoading(false)}}
  async function matchRide(){if(!ride?.id || String(ride.id).startsWith('local-')){setMatch({matched:false,reason:'Matching real exige corrida criada no backend.',estimated_wait_minutes:pricing.estimated_wait_minutes}); return;} setLoading(true);try{setMatch(await apiPost(`/rides/${ride.id}/match`));}catch(e){setMatch({matched:false,reason:'Nenhum motorista disponível ou backend indisponível.',estimated_wait_minutes:pricing.estimated_wait_minutes});}finally{setLoading(false)}}
  return <div className="grid two-one"><Card><div className="row between"><h2><MapPin size={20}/> Passageiro</h2><Pill type={apiStatus==='online'?'success':'warning'}>{apiStatus==='online'?'API online':'Fallback'}</Pill></div><label>Origem</label><select value={origem} onChange={e=>setOrigem(e.target.value)}>{bairros.map(b=><option key={b}>{b}</option>)}</select><label>Destino</label><select value={destino} onChange={e=>setDestino(e.target.value)}>{bairros.map(b=><option key={b}>{b}</option>)}</select><label>Distância km</label><input type="number" value={distanceKm} onChange={e=>setDistanceKm(Number(e.target.value))}/><label>Pessoas</label><input type="number" min="1" max="7" value={occupants} onChange={e=>setOccupants(Number(e.target.value))}/><label className="check"><input type="checkbox" checked={goesBeyondCenter} onChange={e=>setGoesBeyondCenter(e.target.checked)}/> Vai além do centro</label><Button onClick={quote} disabled={loading}>Calcular valor</Button><Button kind="primary" onClick={createRide} disabled={loading}>Chamar De Passagem</Button><Button kind="outline" onClick={matchRide} disabled={!ride||loading}>Buscar motorista</Button>{error&&<div className="alert"><AlertTriangle size={16}/>{error}</div>}</Card><Card><div className="row between"><div><h2>Resumo da corrida</h2><p>Tarifa previsível, sem dinâmica.</p></div><Pill type="dark">{pricing.mode}</Pill></div><div className="stats"><div><Wallet/><span>Por passageiro</span><b>{money(pricing.price_per_passenger)}</b></div><div><Users/><span>Total</span><b>{money(pricing.total_trip_price)}</b></div><div><Clock/><span>Espera</span><b>{pricing.estimated_wait_minutes} min</b></div><div><ShieldCheck/><span>Política</span><b>Sem dinâmica</b></div></div><div className="split"><pre>{JSON.stringify(ride||{status:'ainda não criada'},null,2)}</pre><pre>{JSON.stringify(match||{status:'aguardando busca'},null,2)}</pre></div></Card></div>
}

function Motorista(){const [online,setOnline]=useState(true); const [ret,setRet]=useState(null); async function calc(){try{const d=await apiGet(`/pricing/return-fee?distance_km=10&app_online=${online}`); setRet(d.return_fee)}catch{setRet(online?4.5:0)}} return <div className="grid two-one"><Card><h2><Car size={20}/> Motorista</h2><div className="bigbox"><span>Status</span><b>{online?'Online':'Offline'}</b></div><Button kind={online?'danger':'primary'} onClick={()=>setOnline(!online)}>{online?'Ficar offline':'Ficar online'}</Button><Button onClick={calc}><Navigation size={16}/> Simular taxa de retorno</Button>{ret!==null&&<div className="ok">Taxa protegida: <b>{money(ret)}</b></div>}<p>Se desligar o app durante retorno protegido, perde a taxa e gera evento antifraude.</p></Card><Card><h2>Chamadas disponíveis</h2>{[['Brisas do Catu','Centro',7.5,'Shared Comfort'],['Petrolar','Centro',5.6,'Lotação popular'],['Escola Piloto Centro','Santa Terezinha',0,'Área Escolar']].map((r,i)=><div className="call" key={i}><div><b>{r[0]} → {r[1]}</b><span>{r[3]}</span></div>{r[2]>0&&<Pill type="success">{money(r[2])} por pax</Pill>}<Button>Aceitar</Button></div>)}</Card></div>}
function Escolar(){return <div className="grid cards2">{[['João Pedro',3,'Aguardando dentro da escola'],['Ana Clara',8,'Motorista notificada']].map(a=><Card key={a[0]}><div className="row between"><h2><Bell size={20}/>{a[0]}</h2><Pill type={a[1]<=3?'success':'warning'}>{a[2]}</Pill></div><p>Escola Piloto Centro</p><p>Motorista: Carla Menezes</p><p>ETA: {a[1]} min</p><Button kind={a[1]<=3?'primary':''}>{a[1]<=3?'Liberar aluno':'Manter dentro da escola'}</Button></Card>)}</div>}
function Admin(){const [out,setOut]=useState(null); async function tests(){try{setOut(await apiGet('/tests/rules'))}catch{setOut({error:'API indisponível'})}} async function foz(){try{setOut(await apiGet('/demo/foz'))}catch{setOut({error:'API indisponível'})}} async function seed(){try{setOut(await apiPost('/demo/seed-driver'))}catch{setOut({error:'API indisponível'})}} return <div className="grid two-one"><Card><h2>Admin Operacional</h2><Button onClick={tests}>Rodar testes</Button><Button onClick={seed}>Criar motorista demo</Button><Button onClick={foz}>Demo Foz</Button></Card><Card><h2>Saída da API</h2><pre>{JSON.stringify(out||{status:'aguardando ação'},null,2)}</pre></Card></div>}
function Voz(){return <Card><h2>Atualização futura: voz</h2><p>A voz entra depois do piloto funcional como impacto emocional da marca.</p><div className="voice">“Olá, aqui é o De Passagem. Seu motorista está chegando. O ar-condicionado está agradável para você?”</div></Card>}
function App(){const [tab,setTab]=useState('passageiro'); const tabs={passageiro:<Passageiro/>,motorista:<Motorista/>,escolar:<Escolar/>,admin:<Admin/>,voz:<Voz/>}; return <main><header><div><small>Operação de rua</small><h1>De Passagem</h1><p>Mobilidade compartilhada, tarifa sem dinâmica, área escolar e operação territorial.</p></div><div className="badges"><Pill type="success">Sem dinâmica</Pill><Pill>Até 7 lugares</Pill><Pill type="warning">Área Escolar</Pill></div></header><nav>{Object.keys(tabs).map(k=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{k}</button>)}</nav>{tabs[tab]}</main>}

createRoot(document.getElementById('root')).render(<App/>);
